-- ============================================================
-- MPPMS :: 03_sequences.sql
-- Run As: MPPMS user connected to FREEPDB1
-- ============================================================
SET ECHO ON
SET FEEDBACK ON

PROMPT ============================================================
PROMPT  MPPMS :: Creating Sequences
PROMPT ============================================================

-- PK Sequences
CREATE SEQUENCE SEQ_SUPPLIER_ID   START WITH 1001  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MATERIAL_ID   START WITH 5001  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUCT_ID    START WITH 2001  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOM_ID        START WITH 1     INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOM_DETAIL_ID START WITH 1     INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FORECAST_ID   START WITH 1     INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PLAN_ID       START WITH 1     INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MRP_ID        START WITH 1     INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_ID         START WITH 1     INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PO_ID         START WITH 1     INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PO_ITEM_ID    START WITH 1     INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TRACKING_ID   START WITH 1     INCREMENT BY 1 NOCACHE NOCYCLE;

-- Business Document Number Sequences
CREATE SEQUENCE SEQ_PR_NUMBER     START WITH 10001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PO_NUMBER     START WITH 20001 INCREMENT BY 1 NOCACHE NOCYCLE;

PROMPT [OK] All 14 sequences created.

-- Verification
SELECT sequence_name, min_value, max_value, last_number, increment_by
FROM user_sequences
ORDER BY sequence_name;

PROMPT [SUCCESS] Sequences ready. Next Step: Run 04_triggers.sql
