-- MPPMS :: 06_sample_data_part3.sql
-- MRP Records + Purchase Requisitions + Purchase Orders + Tracking
-- Run As: MPPMS user on FREEPDB1
SET DEFINE OFF
SET FEEDBACK ON

PROMPT === Inserting MRP Records ===
-- MRP for PP-AUG2026-MOTOR (PRD-2001, Plan 1)
INSERT INTO MATERIAL_REQUIREMENT_PLAN (PLAN_ID,MATERIAL_ID,GROSS_REQUIREMENT,AVAILABLE_QTY,SAFETY_STOCK,REQUIRED_DATE,MRP_STATUS)
VALUES ((SELECT PLAN_ID FROM PRODUCTION_PLAN WHERE PLAN_NAME='PP-AUG2026-MOTOR'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5001'),
        1800,400,500,DATE '2026-07-25','CALCULATED');  -- 120 units * 15 KG

INSERT INTO MATERIAL_REQUIREMENT_PLAN (PLAN_ID,MATERIAL_ID,GROSS_REQUIREMENT,AVAILABLE_QTY,SAFETY_STOCK,REQUIRED_DATE,MRP_STATUS)
VALUES ((SELECT PLAN_ID FROM PRODUCTION_PLAN WHERE PLAN_NAME='PP-AUG2026-MOTOR'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5009'),
        120,30,50,DATE '2026-07-25','PR_RAISED');  -- 120 units * 1 EA

INSERT INTO MATERIAL_REQUIREMENT_PLAN (PLAN_ID,MATERIAL_ID,GROSS_REQUIREMENT,AVAILABLE_QTY,SAFETY_STOCK,REQUIRED_DATE,MRP_STATUS)
VALUES ((SELECT PLAN_ID FROM PRODUCTION_PLAN WHERE PLAN_NAME='PP-AUG2026-MOTOR'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5008'),
        240,150,200,DATE '2026-07-25','PR_RAISED');  -- 120 * 2 EA

INSERT INTO MATERIAL_REQUIREMENT_PLAN (PLAN_ID,MATERIAL_ID,GROSS_REQUIREMENT,AVAILABLE_QTY,SAFETY_STOCK,REQUIRED_DATE,MRP_STATUS)
VALUES ((SELECT PLAN_ID FROM PRODUCTION_PLAN WHERE PLAN_NAME='PP-AUG2026-MOTOR'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5011'),
        1920,800,1000,DATE '2026-07-28','CALCULATED');  -- 120 * 16 EA

-- MRP for PP-AUG2026-PANEL (PRD-2002, Plan 2)
INSERT INTO MATERIAL_REQUIREMENT_PLAN (PLAN_ID,MATERIAL_ID,GROSS_REQUIREMENT,AVAILABLE_QTY,SAFETY_STOCK,REQUIRED_DATE,MRP_STATUS)
VALUES ((SELECT PLAN_ID FROM PRODUCTION_PLAN WHERE PLAN_NAME='PP-AUG2026-PANEL'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5010'),
        200,20,30,DATE '2026-07-30','PR_RAISED');  -- 200 * 1 EA

INSERT INTO MATERIAL_REQUIREMENT_PLAN (PLAN_ID,MATERIAL_ID,GROSS_REQUIREMENT,AVAILABLE_QTY,SAFETY_STOCK,REQUIRED_DATE,MRP_STATUS)
VALUES ((SELECT PLAN_ID FROM PRODUCTION_PLAN WHERE PLAN_NAME='PP-AUG2026-PANEL'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5022'),
        200,80,80,DATE '2026-07-30','PR_RAISED');

INSERT INTO MATERIAL_REQUIREMENT_PLAN (PLAN_ID,MATERIAL_ID,GROSS_REQUIREMENT,AVAILABLE_QTY,SAFETY_STOCK,REQUIRED_DATE,MRP_STATUS)
VALUES ((SELECT PLAN_ID FROM PRODUCTION_PLAN WHERE PLAN_NAME='PP-AUG2026-PANEL'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5023'),
        800,100,150,DATE '2026-07-30','CALCULATED');

-- MRP for PP-AUG2026-FRAME (PRD-2004, Plan 4)
INSERT INTO MATERIAL_REQUIREMENT_PLAN (PLAN_ID,MATERIAL_ID,GROSS_REQUIREMENT,AVAILABLE_QTY,SAFETY_STOCK,REQUIRED_DATE,MRP_STATUS)
VALUES ((SELECT PLAN_ID FROM PRODUCTION_PLAN WHERE PLAN_NAME='PP-AUG2026-FRAME'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5001'),
        1250,300,500,DATE '2026-08-05','PR_RAISED');  -- 50 * 25 KG

INSERT INTO MATERIAL_REQUIREMENT_PLAN (PLAN_ID,MATERIAL_ID,GROSS_REQUIREMENT,AVAILABLE_QTY,SAFETY_STOCK,REQUIRED_DATE,MRP_STATUS)
VALUES ((SELECT PLAN_ID FROM PRODUCTION_PLAN WHERE PLAN_NAME='PP-AUG2026-FRAME'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5020'),
        200,80,200,DATE '2026-08-05','CALCULATED');

COMMIT;
PROMPT [OK] 9 MRP records inserted.

PROMPT === Inserting Purchase Requisitions ===
INSERT INTO PURCHASE_REQUISITION (MRP_ID,MATERIAL_ID,REQUESTED_QTY,REQUIRED_DATE,PRIORITY,STATUS,JUSTIFICATION,REQUESTED_BY)
VALUES ((SELECT MRP_ID FROM MATERIAL_REQUIREMENT_PLAN m JOIN PRODUCTION_PLAN p ON m.PLAN_ID=p.PLAN_ID
         WHERE p.PLAN_NAME='PP-AUG2026-MOTOR' AND m.MATERIAL_ID=(SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5009')),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5009'),
        140,DATE '2026-07-25','HIGH','APPROVED','MRP-generated requirement for Aug Motor Plan','PLANNER01');

INSERT INTO PURCHASE_REQUISITION (MRP_ID,MATERIAL_ID,REQUESTED_QTY,REQUIRED_DATE,PRIORITY,STATUS,JUSTIFICATION,REQUESTED_BY)
VALUES ((SELECT MRP_ID FROM MATERIAL_REQUIREMENT_PLAN m JOIN PRODUCTION_PLAN p ON m.PLAN_ID=p.PLAN_ID
         WHERE p.PLAN_NAME='PP-AUG2026-MOTOR' AND m.MATERIAL_ID=(SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5008')),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5008'),
        290,DATE '2026-07-25','HIGH','APPROVED','MRP-generated requirement for Aug Motor Plan','PLANNER01');

INSERT INTO PURCHASE_REQUISITION (MRP_ID,MATERIAL_ID,REQUESTED_QTY,REQUIRED_DATE,PRIORITY,STATUS,JUSTIFICATION,REQUESTED_BY)
VALUES ((SELECT MRP_ID FROM MATERIAL_REQUIREMENT_PLAN m JOIN PRODUCTION_PLAN p ON m.PLAN_ID=p.PLAN_ID
         WHERE p.PLAN_NAME='PP-AUG2026-PANEL' AND m.MATERIAL_ID=(SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5010')),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5010'),
        210,DATE '2026-07-30','HIGH','ORDERED','PCB shortage for Panel production','PLANNER01');

INSERT INTO PURCHASE_REQUISITION (MRP_ID,MATERIAL_ID,REQUESTED_QTY,REQUIRED_DATE,PRIORITY,STATUS,JUSTIFICATION,REQUESTED_BY)
VALUES ((SELECT MRP_ID FROM MATERIAL_REQUIREMENT_PLAN m JOIN PRODUCTION_PLAN p ON m.PLAN_ID=p.PLAN_ID
         WHERE p.PLAN_NAME='PP-AUG2026-PANEL' AND m.MATERIAL_ID=(SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5022')),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5022'),
        200,DATE '2026-07-30','HIGH','APPROVED','Cable harness for Panel Aug Plan','PLANNER01');

INSERT INTO PURCHASE_REQUISITION (MRP_ID,MATERIAL_ID,REQUESTED_QTY,REQUIRED_DATE,PRIORITY,STATUS,JUSTIFICATION,REQUESTED_BY)
VALUES ((SELECT MRP_ID FROM MATERIAL_REQUIREMENT_PLAN m JOIN PRODUCTION_PLAN p ON m.PLAN_ID=p.PLAN_ID
         WHERE p.PLAN_NAME='PP-AUG2026-FRAME' AND m.MATERIAL_ID=(SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5001')),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5001'),
        1450,DATE '2026-08-05','MEDIUM','SUBMITTED','Steel sheet for Hydraulic Frame Plan','PLANNER02');

INSERT INTO PURCHASE_REQUISITION (MATERIAL_ID,REQUESTED_QTY,REQUIRED_DATE,PRIORITY,STATUS,JUSTIFICATION,REQUESTED_BY)
VALUES ((SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5005'),
        500,DATE '2026-08-10','MEDIUM','DRAFT','PP stock replenishment - PP granules below reorder','PLANNER02');

INSERT INTO PURCHASE_REQUISITION (MATERIAL_ID,REQUESTED_QTY,REQUIRED_DATE,PRIORITY,STATUS,JUSTIFICATION,REQUESTED_BY)
VALUES ((SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5004'),
        200,DATE '2026-08-15','LOW','DRAFT','Routine copper wire stock replenishment','PLANNER01');
COMMIT;
PROMPT [OK] 7 Purchase Requisitions inserted.

PROMPT === Inserting Purchase Orders ===
-- PO for Electric Motors (MAT-5009) from Bosch
INSERT INTO PURCHASE_ORDER (PR_ID,SUPPLIER_ID,DELIVERY_DATE,ORDER_STATUS,TERMS,CREATED_BY)
VALUES ((SELECT PR_ID FROM PURCHASE_REQUISITION WHERE MATERIAL_ID=(SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5009') AND STATUS='APPROVED'),
        (SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1003'),
        DATE '2026-08-06','ACKNOWLEDGED','Net 30 days. Delivery to Main Warehouse Gate 2.','BUYER01');

-- PO for Bearings (MAT-5008) from Bosch
INSERT INTO PURCHASE_ORDER (PR_ID,SUPPLIER_ID,DELIVERY_DATE,ORDER_STATUS,TERMS,CREATED_BY)
VALUES ((SELECT PR_ID FROM PURCHASE_REQUISITION WHERE MATERIAL_ID=(SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5008') AND STATUS='APPROVED'),
        (SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1003'),
        DATE '2026-08-04','ISSUED','Net 30 days. Delivery to Main Warehouse.','BUYER01');

-- PO for PCB (MAT-5010) from Mahindra Components
INSERT INTO PURCHASE_ORDER (PR_ID,SUPPLIER_ID,DELIVERY_DATE,ORDER_STATUS,TERMS,CREATED_BY)
VALUES ((SELECT PR_ID FROM PURCHASE_REQUISITION WHERE MATERIAL_ID=(SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5010') AND STATUS='ORDERED'),
        (SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1002'),
        DATE '2026-08-14','PARTIALLY_RECEIVED','Net 45 days. Partial delivery accepted.','BUYER01');

-- PO for Cable Harness (MAT-5022) from Bosch
INSERT INTO PURCHASE_ORDER (PR_ID,SUPPLIER_ID,DELIVERY_DATE,ORDER_STATUS,TERMS,CREATED_BY)
VALUES ((SELECT PR_ID FROM PURCHASE_REQUISITION WHERE MATERIAL_ID=(SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5022') AND STATUS='APPROVED'),
        (SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1003'),
        DATE '2026-08-09','ISSUED','Net 30 days.','BUYER02');

-- Standalone PO for Steel Sheet (MAT-5001) from Tata Steel
INSERT INTO PURCHASE_ORDER (SUPPLIER_ID,DELIVERY_DATE,ORDER_STATUS,TERMS,CREATED_BY)
VALUES ((SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1001'),
        DATE '2026-08-20','DRAFT','Net 30 days. Delivery to Yard Storage.','BUYER02');
COMMIT;
PROMPT [OK] 5 Purchase Orders inserted.

PROMPT === Inserting PO Line Items ===
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,MATERIAL_ID,ORDERED_QTY,UNIT_PRICE)
VALUES ((SELECT PO_ID FROM PURCHASE_ORDER WHERE PO_NUMBER=(SELECT PO_NUMBER FROM PURCHASE_ORDER WHERE ORDER_STATUS='ACKNOWLEDGED' AND SUPPLIER_ID=(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1003') AND ROWNUM=1)),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5009'),140,4500.00);

INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,MATERIAL_ID,ORDERED_QTY,UNIT_PRICE)
VALUES ((SELECT PO_ID FROM PURCHASE_ORDER WHERE ORDER_STATUS='ISSUED' AND SUPPLIER_ID=(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1003') AND ROWNUM=1),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5008'),290,385.00);

INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,MATERIAL_ID,ORDERED_QTY,UNIT_PRICE)
VALUES ((SELECT PO_ID FROM PURCHASE_ORDER WHERE ORDER_STATUS='PARTIALLY_RECEIVED'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5010'),210,8200.00);

INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,MATERIAL_ID,ORDERED_QTY,UNIT_PRICE,RECEIVED_QTY)
VALUES ((SELECT PO_ID FROM PURCHASE_ORDER WHERE ORDER_STATUS='PARTIALLY_RECEIVED'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5023'),500,245.00,250);
COMMIT;
PROMPT [OK] PO Line Items inserted (TOTAL_VALUE is virtual computed).

PROMPT === Inserting Procurement Tracking ===
INSERT INTO PROCUREMENT_TRACKING (PO_ID,EXPECTED_DATE,ACTUAL_DATE,DELIVERY_STATUS,REMARKS,UPDATED_BY)
VALUES ((SELECT PO_ID FROM PURCHASE_ORDER WHERE ORDER_STATUS='ACKNOWLEDGED' AND ROWNUM=1),
        DATE '2026-08-06',NULL,'IN_TRANSIT','Shipment dispatched from Bosch Bangalore. AWB: BLR-2026-1892','BUYER01');

INSERT INTO PROCUREMENT_TRACKING (PO_ID,EXPECTED_DATE,ACTUAL_DATE,DELIVERY_STATUS,REMARKS,UPDATED_BY)
VALUES ((SELECT PO_ID FROM PURCHASE_ORDER WHERE ORDER_STATUS='PARTIALLY_RECEIVED'),
        DATE '2026-08-14',DATE '2026-07-28','PARTIALLY_DELIVERED','100 PCBs received. Balance 110 expected by Aug 14.','BUYER01');

INSERT INTO PROCUREMENT_TRACKING (PO_ID,EXPECTED_DATE,DELIVERY_STATUS,REMARKS,UPDATED_BY)
VALUES ((SELECT PO_ID FROM PURCHASE_ORDER WHERE ORDER_STATUS='ISSUED' AND ROWNUM=1),
        DATE '2026-08-04',NULL,'PENDING','PO issued. Awaiting supplier acknowledgement.','BUYER01');
COMMIT;
PROMPT [OK] 3 Procurement Tracking records inserted.

PROMPT 
PROMPT ============================================================
PROMPT  PHASE 3 COMPLETE - Summary
PROMPT ============================================================
SELECT 'SUPPLIER_MASTER'          AS TABLE_NAME, COUNT(*) AS ROWS FROM SUPPLIER_MASTER UNION ALL
SELECT 'MATERIAL_MASTER',                         COUNT(*) FROM MATERIAL_MASTER         UNION ALL
SELECT 'PRODUCT_MASTER',                          COUNT(*) FROM PRODUCT_MASTER          UNION ALL
SELECT 'BOM_MASTER',                              COUNT(*) FROM BOM_MASTER              UNION ALL
SELECT 'BOM_DETAILS',                             COUNT(*) FROM BOM_DETAILS             UNION ALL
SELECT 'DEMAND_FORECAST',                         COUNT(*) FROM DEMAND_FORECAST         UNION ALL
SELECT 'PRODUCTION_PLAN',                         COUNT(*) FROM PRODUCTION_PLAN         UNION ALL
SELECT 'MATERIAL_REQUIREMENT_PLAN',               COUNT(*) FROM MATERIAL_REQUIREMENT_PLAN UNION ALL
SELECT 'PURCHASE_REQUISITION',                    COUNT(*) FROM PURCHASE_REQUISITION    UNION ALL
SELECT 'PURCHASE_ORDER',                          COUNT(*) FROM PURCHASE_ORDER          UNION ALL
SELECT 'PURCHASE_ORDER_ITEMS',                    COUNT(*) FROM PURCHASE_ORDER_ITEMS    UNION ALL
SELECT 'PROCUREMENT_TRACKING',                    COUNT(*) FROM PROCUREMENT_TRACKING
ORDER BY 1;

PROMPT [SUCCESS] Phase 3 Sample Data Complete. Next Step: Run 07_plsql_packages.sql
