-- MPPMS :: 06_sample_data_part1.sql
-- Suppliers + Materials + Products
-- Run As: MPPMS user on FREEPDB1
SET DEFINE OFF
SET FEEDBACK ON

PROMPT === Inserting Suppliers ===
INSERT INTO SUPPLIER_MASTER (SUPPLIER_CODE,SUPPLIER_NAME,CONTACT_PERSON,EMAIL,PHONE,ADDRESS,LEAD_TIME,VENDOR_RATING,STATUS)
VALUES ('SUP-1001','Tata Steel Ltd','Rajesh Kumar','rajesh@tatasteel.com','9800100001','Mumbai, Maharashtra',7,4.5,'ACTIVE');
INSERT INTO SUPPLIER_MASTER (SUPPLIER_CODE,SUPPLIER_NAME,CONTACT_PERSON,EMAIL,PHONE,ADDRESS,LEAD_TIME,VENDOR_RATING,STATUS)
VALUES ('SUP-1002','Mahindra Components','Suresh Patel','suresh@mahindra.com','9800100002','Pune, Maharashtra',10,4.2,'ACTIVE');
INSERT INTO SUPPLIER_MASTER (SUPPLIER_CODE,SUPPLIER_NAME,CONTACT_PERSON,EMAIL,PHONE,ADDRESS,LEAD_TIME,VENDOR_RATING,STATUS)
VALUES ('SUP-1003','Bosch India Ltd','Priya Sharma','priya@bosch.in','9800100003','Bangalore, Karnataka',5,4.8,'ACTIVE');
INSERT INTO SUPPLIER_MASTER (SUPPLIER_CODE,SUPPLIER_NAME,CONTACT_PERSON,EMAIL,PHONE,ADDRESS,LEAD_TIME,VENDOR_RATING,STATUS)
VALUES ('SUP-1004','Infosys Packaging','Anil Mehta','anil@infopkg.com','9800100004','Chennai, Tamil Nadu',3,3.9,'ACTIVE');
INSERT INTO SUPPLIER_MASTER (SUPPLIER_CODE,SUPPLIER_NAME,CONTACT_PERSON,EMAIL,PHONE,ADDRESS,LEAD_TIME,VENDOR_RATING,STATUS)
VALUES ('SUP-1005','Asian Paints Raw','Kavita Nair','kavita@asianpaints.com','9800100005','Mumbai, Maharashtra',6,4.1,'ACTIVE');
INSERT INTO SUPPLIER_MASTER (SUPPLIER_CODE,SUPPLIER_NAME,CONTACT_PERSON,EMAIL,PHONE,ADDRESS,LEAD_TIME,VENDOR_RATING,STATUS)
VALUES ('SUP-1006','Reliance Polymers','Deepak Singh','deepak@reliance.com','9800100006','Surat, Gujarat',8,4.6,'ACTIVE');
INSERT INTO SUPPLIER_MASTER (SUPPLIER_CODE,SUPPLIER_NAME,CONTACT_PERSON,EMAIL,PHONE,ADDRESS,LEAD_TIME,VENDOR_RATING,STATUS)
VALUES ('SUP-1007','Hero Metals Corp','Sanjay Verma','sanjay@herometals.com','9800100007','Ludhiana, Punjab',12,3.7,'ACTIVE');
INSERT INTO SUPPLIER_MASTER (SUPPLIER_CODE,SUPPLIER_NAME,CONTACT_PERSON,EMAIL,PHONE,ADDRESS,LEAD_TIME,VENDOR_RATING,STATUS)
VALUES ('SUP-1008','BASF India Chemicals','Meena Iyer','meena@basf.in','9800100008','Thane, Maharashtra',4,4.9,'ACTIVE');
INSERT INTO SUPPLIER_MASTER (SUPPLIER_CODE,SUPPLIER_NAME,CONTACT_PERSON,EMAIL,PHONE,ADDRESS,LEAD_TIME,VENDOR_RATING,STATUS)
VALUES ('SUP-1009','Godrej Industries','Ravi Pillai','ravi@godrej.com','9800100009','Mumbai, Maharashtra',9,4.3,'ACTIVE');
INSERT INTO SUPPLIER_MASTER (SUPPLIER_CODE,SUPPLIER_NAME,CONTACT_PERSON,EMAIL,PHONE,ADDRESS,LEAD_TIME,VENDOR_RATING,STATUS)
VALUES ('SUP-1010','Wipro Infrastructure','Anita Roy','anita@wiproinf.com','9800100010','Kolkata, West Bengal',15,3.5,'INACTIVE');
COMMIT;
PROMPT [OK] 10 Suppliers inserted.

PROMPT === Inserting Materials ===
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5001','Hot Rolled Steel Sheet','Raw Material','KG',500,1000,7,85.50,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1001'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5002','Cold Rolled Steel Coil','Raw Material','KG',300,800,7,92.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1001'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5003','Aluminium Ingot 99.5%','Raw Material','KG',200,500,10,225.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1007'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5004','Copper Wire 2.5mm','Raw Material','KG',100,300,5,685.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1007'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5005','Polypropylene Granules','Raw Material','KG',400,900,8,135.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1006'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5006','ABS Plastic Pellets','Raw Material','KG',250,600,8,185.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1006'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5007','Epoxy Resin L-135','Chemical','LTR',50,150,4,1250.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1008'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5008','Industrial Bearing 6205','Component','EA',200,500,10,385.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1003'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5009','Electric Motor 0.5HP','Component','EA',50,100,12,4500.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1003'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5010','Control PCB Assembly','Component','EA',30,80,15,8200.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1002'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5011','M8 Hex Bolt Grade 8.8','Hardware','EA',1000,3000,3,12.50,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1002'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5012','M8 Hex Nut Grade 8','Hardware','EA',1000,3000,3,6.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1002'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5013','Spring Washer M8','Hardware','EA',1000,3000,3,4.50,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1002'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5014','Industrial Lubricant 5L','Consumable','LTR',20,60,5,850.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1005'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5015','Anti-Corrosion Coating','Chemical','LTR',30,80,4,650.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1005'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5016','Corrugated Box 600x400','Packaging','EA',500,1200,3,48.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1004'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5017','Foam Padding Sheet 10mm','Packaging','EA',200,500,3,32.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1004'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5018','PVC Insulation Tape','Consumable','ROLL',100,300,3,35.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1004'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5019','Stainless Steel Shaft 25mm','Component','EA',50,150,9,2200.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1001'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5020','Rubber Gasket 50mm','Component','EA',200,600,5,125.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1009'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5021','Powder Coat Paint Grey','Chemical','KG',30,100,4,480.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1005'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5022','Cable Harness 12V','Component','EA',80,200,10,1850.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1003'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5023','Toggle Switch 15A','Component','EA',150,400,7,245.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1003'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5024','Nylon Gear Module 2','Component','EA',100,250,8,520.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1009'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5025','Silicone Sealant 300ml','Chemical','EA',50,150,3,220.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1008'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5026','LED Indicator Lamp 12V','Component','EA',200,600,5,85.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1003'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5027','Aluminium Extrusion 40x40','Component','MTR',100,300,10,650.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1007'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5028','Acrylic Sheet 3mm','Raw Material','SQM',50,150,5,890.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1006'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5029','Thermal Paste 100g','Consumable','EA',30,80,3,350.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1008'),'ACTIVE');
INSERT INTO MATERIAL_MASTER (MATERIAL_CODE,MATERIAL_NAME,CATEGORY,UNIT_OF_MEASURE,SAFETY_STOCK,REORDER_LEVEL,LEAD_TIME,STANDARD_COST,PREFERRED_SUPPLIER_ID,STATUS)
VALUES ('MAT-5030','Shrink Wrap Film 500m','Packaging','ROLL',20,60,3,1200.00,(SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE SUPPLIER_CODE='SUP-1004'),'ACTIVE');
COMMIT;
PROMPT [OK] 30 Materials inserted.

PROMPT === Inserting Products ===
INSERT INTO PRODUCT_MASTER (PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY,DESCRIPTION,STATUS)
VALUES ('PRD-2001','Industrial Conveyor Motor Unit','Machinery','Heavy-duty conveyor belt motor assembly for industrial use','ACTIVE');
INSERT INTO PRODUCT_MASTER (PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY,DESCRIPTION,STATUS)
VALUES ('PRD-2002','Automated Control Panel 12V','Electrical','12V DC automated control panel with PCB and switches','ACTIVE');
INSERT INTO PRODUCT_MASTER (PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY,DESCRIPTION,STATUS)
VALUES ('PRD-2003','Precision Gear Assembly','Mechanical','High-precision gear assembly for CNC applications','ACTIVE');
INSERT INTO PRODUCT_MASTER (PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY,DESCRIPTION,STATUS)
VALUES ('PRD-2004','Hydraulic Pump Frame','Machinery','Steel fabricated frame for hydraulic pump mounting','ACTIVE');
INSERT INTO PRODUCT_MASTER (PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY,DESCRIPTION,STATUS)
VALUES ('PRD-2005','Plastic Enclosure Unit','Electrical','ABS plastic enclosure for electrical components','ACTIVE');
INSERT INTO PRODUCT_MASTER (PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY,DESCRIPTION,STATUS)
VALUES ('PRD-2006','Aluminium Heat Sink','Electronics','Extruded aluminium heat sink for power electronics','ACTIVE');
INSERT INTO PRODUCT_MASTER (PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY,DESCRIPTION,STATUS)
VALUES ('PRD-2007','Shaft Coupling Assembly','Mechanical','Flexible shaft coupling for motor-to-gearbox connection','ACTIVE');
INSERT INTO PRODUCT_MASTER (PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY,DESCRIPTION,STATUS)
VALUES ('PRD-2008','Industrial Wiring Harness','Electrical','12V complete wiring harness for machinery panels','ACTIVE');
INSERT INTO PRODUCT_MASTER (PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY,DESCRIPTION,STATUS)
VALUES ('PRD-2009','Steel Mounting Bracket Kit','Mechanical','Galvanized steel bracket kit for equipment mounting','ACTIVE');
INSERT INTO PRODUCT_MASTER (PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY,DESCRIPTION,STATUS)
VALUES ('PRD-2010','Composite Seal Kit','Mechanical','Complete seal and gasket kit for hydraulic systems','ACTIVE');
COMMIT;
PROMPT [OK] 10 Products inserted.
PROMPT [SUCCESS] Part 1 Complete. Run 06_sample_data_part2.sql next.
