-- MPPMS :: 06_sample_data_part2.sql
-- BOMs + Demand Forecast + Production Plans
-- Run As: MPPMS user on FREEPDB1
SET DEFINE OFF
SET FEEDBACK ON

PROMPT === Inserting BOM Headers ===
INSERT INTO BOM_MASTER (PRODUCT_ID,VERSION,EFFECTIVE_DATE,STATUS)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2001'),'V1.0',DATE '2025-01-01','ACTIVE');
INSERT INTO BOM_MASTER (PRODUCT_ID,VERSION,EFFECTIVE_DATE,STATUS)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2002'),'V1.0',DATE '2025-01-01','ACTIVE');
INSERT INTO BOM_MASTER (PRODUCT_ID,VERSION,EFFECTIVE_DATE,STATUS)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2003'),'V1.0',DATE '2025-01-01','ACTIVE');
INSERT INTO BOM_MASTER (PRODUCT_ID,VERSION,EFFECTIVE_DATE,STATUS)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2004'),'V1.0',DATE '2025-01-01','ACTIVE');
INSERT INTO BOM_MASTER (PRODUCT_ID,VERSION,EFFECTIVE_DATE,STATUS)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2005'),'V1.0',DATE '2025-01-01','ACTIVE');
COMMIT;
PROMPT [OK] 5 BOM headers inserted.

PROMPT === Inserting BOM Details ===
-- PRD-2001: Industrial Conveyor Motor Unit
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2001' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5001'),15.000,'KG');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2001' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5009'),1.000,'EA');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2001' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5008'),2.000,'EA');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2001' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5019'),1.000,'EA');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2001' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5011'),16.000,'EA');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2001' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5012'),16.000,'EA');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2001' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5014'),0.500,'LTR');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2001' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5021'),0.800,'KG');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2001' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5016'),1.000,'EA');

-- PRD-2002: Automated Control Panel
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2002' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5010'),1.000,'EA');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2002' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5022'),1.000,'EA');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2002' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5023'),4.000,'EA');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2002' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5026'),6.000,'EA');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2002' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5006'),2.500,'KG');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2002' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5018'),2.000,'ROLL');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2002' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5016'),1.000,'EA');

-- PRD-2003: Precision Gear Assembly
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2003' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5024'),4.000,'EA');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2003' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5019'),1.000,'EA');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2003' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5008'),2.000,'EA');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2003' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5014'),0.250,'LTR');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2003' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5011'),8.000,'EA');

-- PRD-2004: Hydraulic Pump Frame
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2004' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5001'),25.000,'KG');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2004' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5002'),10.000,'KG');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2004' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5020'),4.000,'EA');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2004' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5015'),1.000,'LTR');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2004' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5021'),1.500,'KG');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2004' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5011'),24.000,'EA');

-- PRD-2005: Plastic Enclosure Unit
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2005' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5006'),3.000,'KG');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2005' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5025'),0.300,'EA');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2005' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5017'),2.000,'EA');
INSERT INTO BOM_DETAILS (BOM_ID,MATERIAL_ID,QUANTITY_REQUIRED,UNIT_OF_MEASURE)
VALUES ((SELECT BOM_ID FROM BOM_MASTER b JOIN PRODUCT_MASTER p ON b.PRODUCT_ID=p.PRODUCT_ID WHERE p.PRODUCT_CODE='PRD-2005' AND b.VERSION='V1.0'),
        (SELECT MATERIAL_ID FROM MATERIAL_MASTER WHERE MATERIAL_CODE='MAT-5016'),1.000,'EA');
COMMIT;
PROMPT [OK] BOM Details inserted.

PROMPT === Inserting Demand Forecasts (12 months) ===
-- PRD-2001 forecasts
INSERT INTO DEMAND_FORECAST (PRODUCT_ID,FORECAST_PERIOD,FORECAST_QTY,FORECAST_TYPE,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2001'),DATE '2026-08-01',120,'MANUAL','PLANNER01');
INSERT INTO DEMAND_FORECAST (PRODUCT_ID,FORECAST_PERIOD,FORECAST_QTY,FORECAST_TYPE,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2001'),DATE '2026-09-01',135,'MANUAL','PLANNER01');
INSERT INTO DEMAND_FORECAST (PRODUCT_ID,FORECAST_PERIOD,FORECAST_QTY,FORECAST_TYPE,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2001'),DATE '2026-10-01',150,'MANUAL','PLANNER01');
INSERT INTO DEMAND_FORECAST (PRODUCT_ID,FORECAST_PERIOD,FORECAST_QTY,FORECAST_TYPE,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2001'),DATE '2026-11-01',140,'SYSTEM','PLANNER01');
-- PRD-2002 forecasts
INSERT INTO DEMAND_FORECAST (PRODUCT_ID,FORECAST_PERIOD,FORECAST_QTY,FORECAST_TYPE,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2002'),DATE '2026-08-01',200,'MANUAL','PLANNER01');
INSERT INTO DEMAND_FORECAST (PRODUCT_ID,FORECAST_PERIOD,FORECAST_QTY,FORECAST_TYPE,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2002'),DATE '2026-09-01',220,'MANUAL','PLANNER01');
INSERT INTO DEMAND_FORECAST (PRODUCT_ID,FORECAST_PERIOD,FORECAST_QTY,FORECAST_TYPE,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2002'),DATE '2026-10-01',180,'SYSTEM','PLANNER01');
-- PRD-2003 forecasts
INSERT INTO DEMAND_FORECAST (PRODUCT_ID,FORECAST_PERIOD,FORECAST_QTY,FORECAST_TYPE,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2003'),DATE '2026-08-01',80,'MANUAL','PLANNER02');
INSERT INTO DEMAND_FORECAST (PRODUCT_ID,FORECAST_PERIOD,FORECAST_QTY,FORECAST_TYPE,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2003'),DATE '2026-09-01',95,'MANUAL','PLANNER02');
-- PRD-2004 forecasts
INSERT INTO DEMAND_FORECAST (PRODUCT_ID,FORECAST_PERIOD,FORECAST_QTY,FORECAST_TYPE,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2004'),DATE '2026-08-01',50,'MANUAL','PLANNER02');
INSERT INTO DEMAND_FORECAST (PRODUCT_ID,FORECAST_PERIOD,FORECAST_QTY,FORECAST_TYPE,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2004'),DATE '2026-09-01',60,'SYSTEM','PLANNER02');
-- PRD-2005 forecasts
INSERT INTO DEMAND_FORECAST (PRODUCT_ID,FORECAST_PERIOD,FORECAST_QTY,FORECAST_TYPE,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2005'),DATE '2026-08-01',300,'MANUAL','PLANNER01');
INSERT INTO DEMAND_FORECAST (PRODUCT_ID,FORECAST_PERIOD,FORECAST_QTY,FORECAST_TYPE,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2005'),DATE '2026-09-01',350,'MANUAL','PLANNER01');
COMMIT;
PROMPT [OK] 13 Demand Forecast records inserted.

PROMPT === Inserting Production Plans ===
INSERT INTO PRODUCTION_PLAN (PRODUCT_ID,PLAN_NAME,PLANNED_QTY,PLANNED_START_DATE,PLANNED_END_DATE,STATUS,APPROVED_BY,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2001'),
        'PP-AUG2026-MOTOR',120,DATE '2026-08-01',DATE '2026-08-25','APPROVED','MGR001','PLANNER01');
INSERT INTO PRODUCTION_PLAN (PRODUCT_ID,PLAN_NAME,PLANNED_QTY,PLANNED_START_DATE,PLANNED_END_DATE,STATUS,APPROVED_BY,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2002'),
        'PP-AUG2026-PANEL',200,DATE '2026-08-05',DATE '2026-08-28','APPROVED','MGR001','PLANNER01');
INSERT INTO PRODUCTION_PLAN (PRODUCT_ID,PLAN_NAME,PLANNED_QTY,PLANNED_START_DATE,PLANNED_END_DATE,STATUS,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2003'),
        'PP-SEP2026-GEAR',95,DATE '2026-09-01',DATE '2026-09-20','DRAFT','PLANNER02');
INSERT INTO PRODUCTION_PLAN (PRODUCT_ID,PLAN_NAME,PLANNED_QTY,PLANNED_START_DATE,PLANNED_END_DATE,STATUS,APPROVED_BY,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2004'),
        'PP-AUG2026-FRAME',50,DATE '2026-08-10',DATE '2026-08-30','IN_PROGRESS','MGR002','PLANNER02');
INSERT INTO PRODUCTION_PLAN (PRODUCT_ID,PLAN_NAME,PLANNED_QTY,PLANNED_START_DATE,PLANNED_END_DATE,STATUS,CREATED_BY)
VALUES ((SELECT PRODUCT_ID FROM PRODUCT_MASTER WHERE PRODUCT_CODE='PRD-2005'),
        'PP-AUG2026-ENCL',300,DATE '2026-08-01',DATE '2026-08-20','APPROVED','PLANNER01');
COMMIT;
PROMPT [OK] 5 Production Plans inserted.
PROMPT [SUCCESS] Part 2 Complete. Run 06_sample_data_part3.sql next.
