-- ============================================================
-- MPPMS :: 20_inventory_tables.sql
-- Run As: MPPMS user connected to FREEPDB1
-- Purpose: Inventory & Warehouse Management Schema Objects
-- ============================================================
SET ECHO ON
SET FEEDBACK ON
SET DEFINE OFF

PROMPT ============================================================
PROMPT  MPPMS :: Phase 13 - Creating Inventory & Warehouse Tables
PROMPT ============================================================

-- ------------------------------------------------------------
-- 1. WAREHOUSE_MASTER
-- ------------------------------------------------------------
CREATE TABLE WAREHOUSE_MASTER (
    WAREHOUSE_ID     NUMBER         NOT NULL,
    WAREHOUSE_CODE   VARCHAR2(20)   NOT NULL,
    WAREHOUSE_NAME   VARCHAR2(100)  NOT NULL,
    PLANT_LOCATION   VARCHAR2(100)  NOT NULL,
    WAREHOUSE_TYPE   VARCHAR2(30)   DEFAULT 'RAW_MATERIAL' NOT NULL,
    MANAGER_NAME     VARCHAR2(100),
    STATUS           VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
    CREATED_DATE     DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_WAREHOUSE PRIMARY KEY (WAREHOUSE_ID),
    CONSTRAINT UQ_WAREHOUSE_CODE UNIQUE (WAREHOUSE_CODE),
    CONSTRAINT CK_WH_TYPE CHECK (WAREHOUSE_TYPE IN ('RAW_MATERIAL','FINISHED_GOODS','SPARE_PARTS','SCRAP','TRANSIT')),
    CONSTRAINT CK_WH_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE'))
);

-- ------------------------------------------------------------
-- 2. STORAGE_BIN
-- ------------------------------------------------------------
CREATE TABLE STORAGE_BIN (
    BIN_ID           NUMBER         NOT NULL,
    WAREHOUSE_ID     NUMBER         NOT NULL,
    BIN_CODE         VARCHAR2(30)   NOT NULL,
    ZONE_NAME        VARCHAR2(50)   DEFAULT 'ZONE-A',
    MAX_CAPACITY     NUMBER         DEFAULT 10000,
    STATUS           VARCHAR2(20)   DEFAULT 'AVAILABLE' NOT NULL,
    CREATED_DATE     DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_STORAGE_BIN PRIMARY KEY (BIN_ID),
    CONSTRAINT FK_BIN_WH FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE_MASTER(WAREHOUSE_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_BIN_CODE UNIQUE (WAREHOUSE_ID, BIN_CODE),
    CONSTRAINT CK_BIN_STATUS CHECK (STATUS IN ('AVAILABLE','FULL','BLOCKED','MAINTENANCE'))
);

-- ------------------------------------------------------------
-- 3. INVENTORY_BALANCE (Stock Ledger)
-- ------------------------------------------------------------
CREATE TABLE INVENTORY_BALANCE (
    BALANCE_ID       NUMBER         NOT NULL,
    MATERIAL_ID      NUMBER         NOT NULL,
    WAREHOUSE_ID     NUMBER         NOT NULL,
    BIN_ID           NUMBER         NOT NULL,
    QTY_ON_HAND      NUMBER         DEFAULT 0 NOT NULL,
    QTY_RESERVED     NUMBER         DEFAULT 0 NOT NULL,
    QTY_IN_QUALITY   NUMBER         DEFAULT 0 NOT NULL,
    QTY_BLOCKED      NUMBER         DEFAULT 0 NOT NULL,
    LAST_UPDATED_DATE DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_INVENTORY_BAL PRIMARY KEY (BALANCE_ID),
    CONSTRAINT FK_BAL_MATERIAL FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAL_MASTER(MATERIAL_ID) ON DELETE CASCADE,
    CONSTRAINT FK_BAL_WH FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE_MASTER(WAREHOUSE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_BAL_BIN FOREIGN KEY (BIN_ID) REFERENCES STORAGE_BIN(BIN_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_BAL_MAT_BIN UNIQUE (MATERIAL_ID, WAREHOUSE_ID, BIN_ID),
    CONSTRAINT CK_BAL_QTY_ON_HAND CHECK (QTY_ON_HAND >= 0),
    CONSTRAINT CK_BAL_QTY_RESERVED CHECK (QTY_RESERVED >= 0),
    CONSTRAINT CK_BAL_QTY_QUALITY CHECK (QTY_IN_QUALITY >= 0),
    CONSTRAINT CK_BAL_QTY_BLOCKED CHECK (QTY_BLOCKED >= 0)
);

-- ------------------------------------------------------------
-- 4. INVENTORY_TRANSACTION (Goods Movement Ledger - MIGO equivalent)
-- ------------------------------------------------------------
CREATE TABLE INVENTORY_TRANSACTION (
    TRANSACTION_ID   NUMBER         NOT NULL,
    TRANSACTION_NUM  VARCHAR2(30)   NOT NULL,
    MOVEMENT_CODE    VARCHAR2(10)   NOT NULL, -- 101: GR PO, 261: GI PROD, 311: TRANSFER, 551: SCRAP
    TRANSACTION_TYPE VARCHAR2(30)   NOT NULL, -- GOODS_RECEIPT, GOODS_ISSUE, TRANSFER, ADJUSTMENT
    MATERIAL_ID      NUMBER         NOT NULL,
    WAREHOUSE_ID     NUMBER         NOT NULL,
    BIN_ID           NUMBER         NOT NULL,
    QUANTITY         NUMBER         NOT NULL,
    REFERENCE_TYPE   VARCHAR2(30),             -- PO, PRODUCTION_PLAN, REQUISITION, AUDIT
    REFERENCE_ID     NUMBER,
    PERFORMED_BY     VARCHAR2(100)  DEFAULT USER NOT NULL,
    REMARKS          VARCHAR2(255),
    TRANSACTION_DATE DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_INV_TXN PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT UQ_INV_TXN_NUM UNIQUE (TRANSACTION_NUM),
    CONSTRAINT FK_TXN_MATERIAL FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAL_MASTER(MATERIAL_ID),
    CONSTRAINT FK_TXN_WH FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE_MASTER(WAREHOUSE_ID),
    CONSTRAINT FK_TXN_BIN FOREIGN KEY (BIN_ID) REFERENCES STORAGE_BIN(BIN_ID),
    CONSTRAINT CK_TXN_TYPE CHECK (TRANSACTION_TYPE IN ('GOODS_RECEIPT','GOODS_ISSUE','TRANSFER','ADJUSTMENT'))
);

-- ------------------------------------------------------------
-- SEQUENCES
-- ------------------------------------------------------------
CREATE SEQUENCE SEQ_WAREHOUSE_ID   START WITH 201 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BIN_ID         START WITH 601 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BALANCE_ID     START WITH 2001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TRANSACTION_ID START WITH 9001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TXN_NUMBER     START WITH 10001 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ------------------------------------------------------------
-- TRIGGERS
-- ------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_WAREHOUSE_BI
    BEFORE INSERT ON WAREHOUSE_MASTER
    FOR EACH ROW
BEGIN
    IF :NEW.WAREHOUSE_ID IS NULL THEN
        :NEW.WAREHOUSE_ID := SEQ_WAREHOUSE_ID.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIN_BI
    BEFORE INSERT ON STORAGE_BIN
    FOR EACH ROW
BEGIN
    IF :NEW.BIN_ID IS NULL THEN
        :NEW.BIN_ID := SEQ_BIN_ID.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BALANCE_BI
    BEFORE INSERT ON INVENTORY_BALANCE
    FOR EACH ROW
BEGIN
    IF :NEW.BALANCE_ID IS NULL THEN
        :NEW.BALANCE_ID := SEQ_BALANCE_ID.NEXTVAL;
    END IF;
    :NEW.LAST_UPDATED_DATE := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER TRG_TRANSACTION_BI
    BEFORE INSERT ON INVENTORY_TRANSACTION
    FOR EACH ROW
BEGIN
    IF :NEW.TRANSACTION_ID IS NULL THEN
        :NEW.TRANSACTION_ID := SEQ_TRANSACTION_ID.NEXTVAL;
    END IF;
    IF :NEW.TRANSACTION_NUM IS NULL THEN
        :NEW.TRANSACTION_NUM := 'TXN-' || TO_CHAR(SYSDATE,'YYYY') || '-' || LPAD(SEQ_TXN_NUMBER.NEXTVAL, 6, '0');
    END IF;
    IF :NEW.TRANSACTION_DATE IS NULL THEN
        :NEW.TRANSACTION_DATE := SYSDATE;
    END IF;
END;
/

-- ------------------------------------------------------------
-- INDEXES
-- ------------------------------------------------------------
CREATE INDEX IDX_BIN_WH ON STORAGE_BIN(WAREHOUSE_ID);
CREATE INDEX IDX_BAL_MAT ON INVENTORY_BALANCE(MATERIAL_ID);
CREATE INDEX IDX_BAL_WH ON INVENTORY_BALANCE(WAREHOUSE_ID);
CREATE INDEX IDX_BAL_BIN ON INVENTORY_BALANCE(BIN_ID);
CREATE INDEX IDX_TXN_MAT ON INVENTORY_TRANSACTION(MATERIAL_ID);
CREATE INDEX IDX_TXN_WH ON INVENTORY_TRANSACTION(WAREHOUSE_ID);
CREATE INDEX IDX_TXN_DATE ON INVENTORY_TRANSACTION(TRANSACTION_DATE DESC);

PROMPT [SUCCESS] Inventory & Warehouse tables, sequences, triggers, and indexes created.
