-- ============================================================
-- MPPMS :: 35_vendor_scorecard_tables.sql
-- Purpose : Vendor Scorecard & Delivery Event Tracking
-- Run As  : MPPMS user on FREEPDB1
-- ============================================================
SET ECHO ON
SET FEEDBACK ON
SET DEFINE OFF

PROMPT ============================================================
PROMPT  MPPMS :: Phase 11a - Vendor Scorecard Tables
PROMPT ============================================================

-- ── Currency Master (shared across all modules) ─────────────
CREATE TABLE CURRENCY_MASTER (
    CURRENCY_CODE   VARCHAR2(3)    NOT NULL,
    CURRENCY_NAME   VARCHAR2(60)   NOT NULL,
    CURRENCY_SYMBOL VARCHAR2(5),
    IS_BASE         VARCHAR2(1)    DEFAULT 'N',   -- Y = INR is base
    IS_ACTIVE       VARCHAR2(1)    DEFAULT 'Y',
    CONSTRAINT PK_CURRENCY PRIMARY KEY (CURRENCY_CODE)
);

-- ── Exchange Rates (daily snapshot) ─────────────────────────
CREATE TABLE EXCHANGE_RATE (
    RATE_ID         NUMBER         GENERATED ALWAYS AS IDENTITY,
    FROM_CURRENCY   VARCHAR2(3)    NOT NULL,
    TO_CURRENCY     VARCHAR2(3)    NOT NULL,
    RATE            NUMBER(18,6)   NOT NULL,
    RATE_DATE       DATE           NOT NULL,
    SOURCE          VARCHAR2(30)   DEFAULT 'MANUAL',  -- MANUAL / API
    CREATED_DATE    DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_EXCHANGE_RATE  PRIMARY KEY (RATE_ID),
    CONSTRAINT FK_ER_FROM        FOREIGN KEY (FROM_CURRENCY) REFERENCES CURRENCY_MASTER(CURRENCY_CODE),
    CONSTRAINT FK_ER_TO          FOREIGN KEY (TO_CURRENCY)   REFERENCES CURRENCY_MASTER(CURRENCY_CODE),
    CONSTRAINT UQ_EXCHANGE_RATE  UNIQUE (FROM_CURRENCY, TO_CURRENCY, RATE_DATE)
);

-- ── Supplier Scorecard (monthly calculated) ──────────────────
CREATE TABLE SUPPLIER_SCORECARD (
    SCORECARD_ID            NUMBER         GENERATED ALWAYS AS IDENTITY,
    SUPPLIER_ID             NUMBER         NOT NULL,
    PERIOD_MONTH            NUMBER(2)      NOT NULL,   -- 1-12
    PERIOD_YEAR             NUMBER(4)      NOT NULL,
    -- Delivery metrics (40 pts)
    TOTAL_PO_LINES          NUMBER         DEFAULT 0,
    ON_TIME_LINES           NUMBER         DEFAULT 0,
    LATE_LINES              NUMBER         DEFAULT 0,
    AVG_DAYS_LATE           NUMBER(6,2)    DEFAULT 0,
    DELIVERY_SCORE          NUMBER(5,2)    DEFAULT 0,   -- 0-40
    -- Quality metrics (35 pts)
    TOTAL_LOTS_RECEIVED     NUMBER         DEFAULT 0,
    LOTS_ACCEPTED           NUMBER         DEFAULT 0,
    LOTS_REJECTED           NUMBER         DEFAULT 0,
    REJECTION_RATE_PCT      NUMBER(6,3)    DEFAULT 0,
    QUALITY_SCORE           NUMBER(5,2)    DEFAULT 0,   -- 0-35
    -- Pricing metrics (25 pts)
    TOTAL_PO_VALUE          NUMBER(18,2)   DEFAULT 0,
    TOTAL_INVOICE_VALUE     NUMBER(18,2)   DEFAULT 0,
    PRICE_VARIANCE_PCT      NUMBER(6,3)    DEFAULT 0,
    PRICE_SCORE             NUMBER(5,2)    DEFAULT 0,   -- 0-25
    -- Summary
    OVERALL_SCORE           NUMBER(5,2)    DEFAULT 0,   -- 0-100
    RATING                  VARCHAR2(1),                -- A/B/C/D
    CALCULATED_DATE         DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_SCORECARD       PRIMARY KEY (SCORECARD_ID),
    CONSTRAINT FK_SC_SUPPLIER     FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER_MASTER(SUPPLIER_ID),
    CONSTRAINT UQ_SCORECARD       UNIQUE (SUPPLIER_ID, PERIOD_MONTH, PERIOD_YEAR),
    CONSTRAINT CHK_SC_MONTH       CHECK (PERIOD_MONTH BETWEEN 1 AND 12),
    CONSTRAINT CHK_SC_RATING      CHECK (RATING IN ('A','B','C','D'))
);

-- ── Delivery Events (individual PO line delivery records) ────
CREATE TABLE DELIVERY_EVENT (
    EVENT_ID            NUMBER         GENERATED ALWAYS AS IDENTITY,
    PO_ID               NUMBER         NOT NULL,
    PO_LINE_ID          NUMBER,
    SUPPLIER_ID         NUMBER         NOT NULL,
    MATERIAL_ID         NUMBER,
    PROMISED_DATE       DATE           NOT NULL,
    ACTUAL_DATE         DATE,
    DAYS_LATE           NUMBER(5)      DEFAULT 0,
    QTY_ORDERED         NUMBER(18,3)   NOT NULL,
    QTY_DELIVERED       NUMBER(18,3)   DEFAULT 0,
    DELIVERY_STATUS     VARCHAR2(20)   DEFAULT 'PENDING',
    CREATED_DATE        DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_DELIVERY_EVENT  PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_DE_PO           FOREIGN KEY (PO_ID)       REFERENCES PURCHASE_ORDER(PO_ID),
    CONSTRAINT FK_DE_SUPPLIER     FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER_MASTER(SUPPLIER_ID),
    CONSTRAINT FK_DE_MATERIAL     FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAL_MASTER(MATERIAL_ID),
    CONSTRAINT CHK_DE_STATUS      CHECK (DELIVERY_STATUS IN ('PENDING','ON_TIME','LATE','PARTIAL','CANCELLED'))
);

-- ── Indexes ──────────────────────────────────────────────────
CREATE INDEX IDX_SCORECARD_SUPPLIER ON SUPPLIER_SCORECARD(SUPPLIER_ID);
CREATE INDEX IDX_SCORECARD_PERIOD   ON SUPPLIER_SCORECARD(PERIOD_YEAR, PERIOD_MONTH);
CREATE INDEX IDX_DEL_EVENT_SUPP     ON DELIVERY_EVENT(SUPPLIER_ID);
CREATE INDEX IDX_DEL_EVENT_PO       ON DELIVERY_EVENT(PO_ID);
CREATE INDEX IDX_EXRATE_DATE        ON EXCHANGE_RATE(RATE_DATE, FROM_CURRENCY, TO_CURRENCY);

-- ── Seed currency data ───────────────────────────────────────
INSERT INTO CURRENCY_MASTER VALUES ('INR', 'Indian Rupee',           '₹',  'Y', 'Y');
INSERT INTO CURRENCY_MASTER VALUES ('SAR', 'Saudi Arabian Riyal',    '﷼',  'N', 'Y');
INSERT INTO CURRENCY_MASTER VALUES ('USD', 'US Dollar',              '$',  'N', 'Y');
INSERT INTO CURRENCY_MASTER VALUES ('EUR', 'Euro',                   '€',  'N', 'Y');
INSERT INTO CURRENCY_MASTER VALUES ('AED', 'UAE Dirham',             'د.إ','N', 'Y');

-- Seed current exchange rates (INR base)
INSERT INTO EXCHANGE_RATE (FROM_CURRENCY, TO_CURRENCY, RATE, RATE_DATE)
    VALUES ('USD','INR', 83.920000, TRUNC(SYSDATE));
INSERT INTO EXCHANGE_RATE (FROM_CURRENCY, TO_CURRENCY, RATE, RATE_DATE)
    VALUES ('SAR','INR', 22.380000, TRUNC(SYSDATE));
INSERT INTO EXCHANGE_RATE (FROM_CURRENCY, TO_CURRENCY, RATE, RATE_DATE)
    VALUES ('EUR','INR', 91.150000, TRUNC(SYSDATE));
INSERT INTO EXCHANGE_RATE (FROM_CURRENCY, TO_CURRENCY, RATE, RATE_DATE)
    VALUES ('AED','INR', 22.850000, TRUNC(SYSDATE));
INSERT INTO EXCHANGE_RATE (FROM_CURRENCY, TO_CURRENCY, RATE, RATE_DATE)
    VALUES ('INR','USD',  0.011917, TRUNC(SYSDATE));
INSERT INTO EXCHANGE_RATE (FROM_CURRENCY, TO_CURRENCY, RATE, RATE_DATE)
    VALUES ('INR','SAR',  0.044681, TRUNC(SYSDATE));

COMMIT;

PROMPT [OK] Vendor Scorecard tables created.
SELECT TABLE_NAME FROM USER_TABLES
WHERE TABLE_NAME IN ('CURRENCY_MASTER','EXCHANGE_RATE','SUPPLIER_SCORECARD','DELIVERY_EVENT')
ORDER BY TABLE_NAME;
