-- ============================================================
-- MPPMS :: 37_asl_tables.sql
-- Purpose : Approved Supplier List & Material Certifications
-- Run As  : MPPMS user on FREEPDB1
-- ============================================================
SET ECHO ON
SET FEEDBACK ON
SET DEFINE OFF

PROMPT ============================================================
PROMPT  MPPMS :: Phase 11b - ASL Tables
PROMPT ============================================================

CREATE TABLE APPROVED_SUPPLIER_LIST (
    ASL_ID              NUMBER         GENERATED ALWAYS AS IDENTITY,
    MATERIAL_ID         NUMBER         NOT NULL,
    SUPPLIER_ID         NUMBER         NOT NULL,
    APPROVAL_STATUS     VARCHAR2(20)   DEFAULT 'APPROVED',
    PREFERENCE_RANK     NUMBER(1)      DEFAULT 1,   -- 1=preferred, 2=backup, 3=alternate
    APPROVED_BY         VARCHAR2(60),
    APPROVED_DATE       DATE,
    EXPIRY_DATE         DATE,
    MIN_ORDER_QTY       NUMBER(18,3),
    MAX_ORDER_QTY       NUMBER(18,3),
    LEAD_TIME_DAYS      NUMBER(3),
    UNIT_PRICE_AGREED   NUMBER(18,4),
    CURRENCY_CODE       VARCHAR2(3)    DEFAULT 'INR',
    NOTES               VARCHAR2(1000),
    CREATED_DATE        DATE           DEFAULT SYSDATE,
    UPDATED_DATE        DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_ASL             PRIMARY KEY (ASL_ID),
    CONSTRAINT FK_ASL_MATERIAL    FOREIGN KEY (MATERIAL_ID)  REFERENCES MATERIAL_MASTER(MATERIAL_ID),
    CONSTRAINT FK_ASL_SUPPLIER    FOREIGN KEY (SUPPLIER_ID)  REFERENCES SUPPLIER_MASTER(SUPPLIER_ID),
    CONSTRAINT FK_ASL_CURRENCY    FOREIGN KEY (CURRENCY_CODE) REFERENCES CURRENCY_MASTER(CURRENCY_CODE),
    CONSTRAINT UQ_ASL             UNIQUE (MATERIAL_ID, SUPPLIER_ID),
    CONSTRAINT CHK_ASL_STATUS     CHECK (APPROVAL_STATUS IN ('APPROVED','CONDITIONAL','BLOCKED','PENDING_REVIEW')),
    CONSTRAINT CHK_ASL_RANK       CHECK (PREFERENCE_RANK IN (1,2,3))
);

CREATE TABLE SUPPLIER_MATERIAL_CERT (
    CERT_ID             NUMBER         GENERATED ALWAYS AS IDENTITY,
    ASL_ID              NUMBER         NOT NULL,
    CERT_TYPE           VARCHAR2(60)   NOT NULL,  -- ISO9001, ARAMCO_APPROVED, etc.
    CERT_NUMBER         VARCHAR2(100),
    ISSUED_BY           VARCHAR2(200),
    ISSUE_DATE          DATE,
    EXPIRY_DATE         DATE,
    CERT_STATUS         VARCHAR2(20)   DEFAULT 'ACTIVE',
    DOC_REFERENCE       VARCHAR2(200),
    CREATED_DATE        DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_SUPP_CERT       PRIMARY KEY (CERT_ID),
    CONSTRAINT FK_CERT_ASL        FOREIGN KEY (ASL_ID) REFERENCES APPROVED_SUPPLIER_LIST(ASL_ID),
    CONSTRAINT CHK_CERT_STATUS    CHECK (CERT_STATUS IN ('ACTIVE','EXPIRED','REVOKED','PENDING'))
);

-- Indexes
CREATE INDEX IDX_ASL_MATERIAL    ON APPROVED_SUPPLIER_LIST(MATERIAL_ID);
CREATE INDEX IDX_ASL_SUPPLIER    ON APPROVED_SUPPLIER_LIST(SUPPLIER_ID);
CREATE INDEX IDX_ASL_STATUS      ON APPROVED_SUPPLIER_LIST(APPROVAL_STATUS);
CREATE INDEX IDX_CERT_ASL        ON SUPPLIER_MATERIAL_CERT(ASL_ID);
CREATE INDEX IDX_CERT_EXPIRY     ON SUPPLIER_MATERIAL_CERT(EXPIRY_DATE);

-- Seed realistic ASL data for Zamil Steel materials
DECLARE
    PROCEDURE add_asl(p_mat VARCHAR2, p_supp VARCHAR2, p_rank NUMBER,
                      p_price NUMBER, p_curr VARCHAR2, p_lead NUMBER) IS
        v_mat_id  NUMBER;
        v_supp_id NUMBER;
    BEGIN
        SELECT MATERIAL_ID INTO v_mat_id  FROM MATERIAL_MASTER  WHERE MATERIAL_CODE = p_mat;
        SELECT SUPPLIER_ID INTO v_supp_id FROM SUPPLIER_MASTER  WHERE ROWNUM = 1
          AND SUPPLIER_ID >= p_supp;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
BEGIN
    -- Seed a few ASL entries using known material IDs
    FOR m IN (SELECT MATERIAL_ID, MATERIAL_CODE FROM MATERIAL_MASTER WHERE ROWNUM <= 10) LOOP
        FOR s IN (SELECT SUPPLIER_ID FROM SUPPLIER_MASTER WHERE ROWNUM <= 2) LOOP
            BEGIN
                INSERT INTO APPROVED_SUPPLIER_LIST (
                    MATERIAL_ID, SUPPLIER_ID, APPROVAL_STATUS, PREFERENCE_RANK,
                    APPROVED_BY, APPROVED_DATE, EXPIRY_DATE,
                    LEAD_TIME_DAYS, CURRENCY_CODE, NOTES
                ) VALUES (
                    m.MATERIAL_ID, s.SUPPLIER_ID, 'APPROVED',
                    CASE WHEN s.SUPPLIER_ID = (SELECT MIN(SUPPLIER_ID) FROM SUPPLIER_MASTER) THEN 1 ELSE 2 END,
                    'PROCUREMENT_MANAGER', TRUNC(SYSDATE) - 90, TRUNC(SYSDATE) + 270,
                    30, 'SAR', 'Auto-seeded ASL entry for ' || m.MATERIAL_CODE
                );
            EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
            END;
        END LOOP;
    END LOOP;
    COMMIT;
END;
/

PROMPT [OK] ASL tables created and seeded.
SELECT TABLE_NAME FROM USER_TABLES
WHERE TABLE_NAME IN ('APPROVED_SUPPLIER_LIST','SUPPLIER_MATERIAL_CERT')
ORDER BY TABLE_NAME;
