-- ============================================================
-- MPPMS :: 39_invoice_matching_tables.sql
-- Purpose : Supplier Invoices & 3-Way AP Matching
-- Run As  : MPPMS user on FREEPDB1
-- ============================================================
SET ECHO ON
SET FEEDBACK ON
SET DEFINE OFF

PROMPT ============================================================
PROMPT  MPPMS :: Phase 11c - Invoice Matching Tables
PROMPT ============================================================

CREATE TABLE PAYMENT_TERM (
    TERM_ID         NUMBER          GENERATED ALWAYS AS IDENTITY,
    TERM_CODE       VARCHAR2(20)    NOT NULL,
    TERM_NAME       VARCHAR2(100)   NOT NULL,
    NET_DAYS        NUMBER(3)       DEFAULT 30,
    DISCOUNT_DAYS   NUMBER(3),
    DISCOUNT_PCT    NUMBER(5,2)     DEFAULT 0,
    DESCRIPTION     VARCHAR2(200),
    IS_ACTIVE       VARCHAR2(1)     DEFAULT 'Y',
    CONSTRAINT PK_PAYMENT_TERM  PRIMARY KEY (TERM_ID),
    CONSTRAINT UQ_TERM_CODE     UNIQUE (TERM_CODE)
);

CREATE TABLE SUPPLIER_INVOICE (
    INVOICE_ID          NUMBER          GENERATED ALWAYS AS IDENTITY,
    INVOICE_NUMBER      VARCHAR2(50)    NOT NULL,
    SUPPLIER_ID         NUMBER          NOT NULL,
    INVOICE_DATE        DATE            NOT NULL,
    DUE_DATE            DATE,
    CURRENCY_CODE       VARCHAR2(3)     DEFAULT 'SAR',
    EXCHANGE_RATE       NUMBER(18,6)    DEFAULT 1,
    SUBTOTAL_AMOUNT     NUMBER(18,2)    DEFAULT 0,
    TAX_AMOUNT          NUMBER(18,2)    DEFAULT 0,
    TOTAL_AMOUNT        NUMBER(18,2)    DEFAULT 0,
    TOTAL_AMOUNT_INR    NUMBER(18,2)    DEFAULT 0,   -- converted to base
    PAYMENT_TERM_ID     NUMBER,
    STATUS              VARCHAR2(20)    DEFAULT 'DRAFT',
    MATCH_STATUS        VARCHAR2(30)    DEFAULT 'UNMATCHED',
    APPROVED_BY         VARCHAR2(60),
    APPROVED_DATE       DATE,
    PAID_DATE           DATE,
    PAYMENT_REFERENCE   VARCHAR2(100),
    NOTES               VARCHAR2(1000),
    CREATED_BY          VARCHAR2(60)    DEFAULT USER,
    CREATED_DATE        DATE            DEFAULT SYSDATE,
    UPDATED_DATE        DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_INVOICE           PRIMARY KEY (INVOICE_ID),
    CONSTRAINT FK_INV_SUPPLIER      FOREIGN KEY (SUPPLIER_ID)    REFERENCES SUPPLIER_MASTER(SUPPLIER_ID),
    CONSTRAINT FK_INV_CURRENCY      FOREIGN KEY (CURRENCY_CODE)  REFERENCES CURRENCY_MASTER(CURRENCY_CODE),
    CONSTRAINT FK_INV_TERM          FOREIGN KEY (PAYMENT_TERM_ID) REFERENCES PAYMENT_TERM(TERM_ID),
    CONSTRAINT UQ_INVOICE_NUM       UNIQUE (SUPPLIER_ID, INVOICE_NUMBER),
    CONSTRAINT CHK_INV_STATUS       CHECK (STATUS IN ('DRAFT','SUBMITTED','IN_REVIEW','APPROVED','REJECTED','PAID','CANCELLED')),
    CONSTRAINT CHK_INV_MATCH        CHECK (MATCH_STATUS IN ('UNMATCHED','PARTIAL_MATCH','MATCHED','VARIANCE_FLAGGED','OVERRIDE_APPROVED'))
);

CREATE TABLE INVOICE_LINE (
    LINE_ID             NUMBER          GENERATED ALWAYS AS IDENTITY,
    INVOICE_ID          NUMBER          NOT NULL,
    LINE_NUMBER         NUMBER(3)       NOT NULL,
    PO_ID               NUMBER,
    PO_LINE_ID          NUMBER,
    MATERIAL_ID         NUMBER,
    DESCRIPTION         VARCHAR2(500),
    INVOICED_QTY        NUMBER(18,3)    NOT NULL,
    UNIT_OF_MEASURE     VARCHAR2(10),
    INVOICED_UNIT_PRICE NUMBER(18,4)    NOT NULL,
    LINE_AMOUNT         NUMBER(18,2)    NOT NULL,
    CURRENCY_CODE       VARCHAR2(3),
    TAX_PCT             NUMBER(5,2)     DEFAULT 0,
    TAX_AMOUNT          NUMBER(18,2)    DEFAULT 0,
    MATCH_STATUS        VARCHAR2(30)    DEFAULT 'UNMATCHED',
    CONSTRAINT PK_INVOICE_LINE      PRIMARY KEY (LINE_ID),
    CONSTRAINT FK_IL_INVOICE        FOREIGN KEY (INVOICE_ID)   REFERENCES SUPPLIER_INVOICE(INVOICE_ID),
    CONSTRAINT FK_IL_PO             FOREIGN KEY (PO_ID)        REFERENCES PURCHASE_ORDER(PO_ID),
    CONSTRAINT FK_IL_MATERIAL       FOREIGN KEY (MATERIAL_ID)  REFERENCES MATERIAL_MASTER(MATERIAL_ID)
);

CREATE TABLE INVOICE_MATCH (
    MATCH_ID                NUMBER          GENERATED ALWAYS AS IDENTITY,
    INVOICE_ID              NUMBER          NOT NULL,
    INVOICE_LINE_ID         NUMBER          NOT NULL,
    PO_ID                   NUMBER,
    PO_LINE_ID              NUMBER,
    GR_TRANSACTION_ID       NUMBER,         -- links to INVENTORY_TRANSACTION
    -- PO leg
    PO_AGREED_PRICE         NUMBER(18,4),
    PO_QTY                  NUMBER(18,3),
    -- GR leg
    GR_QTY_RECEIVED         NUMBER(18,3),
    -- Invoice leg
    INVOICE_QTY             NUMBER(18,3),
    INVOICE_UNIT_PRICE      NUMBER(18,4),
    -- Variances
    QTY_VARIANCE            NUMBER(18,3),   -- GR qty - Invoice qty
    PRICE_VARIANCE          NUMBER(18,4),   -- Invoice price - PO agreed price
    QTY_VARIANCE_PCT        NUMBER(6,3),
    PRICE_VARIANCE_PCT      NUMBER(6,3),
    -- Result
    MATCH_STATUS            VARCHAR2(30)    DEFAULT 'UNMATCHED',
    -- MATCHED / QTY_VARIANCE / PRICE_VARIANCE / BOTH_VARIANCE / WITHIN_TOLERANCE
    TOLERANCE_APPLIED       VARCHAR2(1)     DEFAULT 'N',
    MATCHED_DATE            DATE,
    MATCHED_BY              VARCHAR2(60),
    OVERRIDE_REASON         VARCHAR2(500),
    CONSTRAINT PK_INVOICE_MATCH     PRIMARY KEY (MATCH_ID),
    CONSTRAINT FK_IM_INVOICE        FOREIGN KEY (INVOICE_ID)      REFERENCES SUPPLIER_INVOICE(INVOICE_ID),
    CONSTRAINT FK_IM_INV_LINE       FOREIGN KEY (INVOICE_LINE_ID) REFERENCES INVOICE_LINE(LINE_ID)
);

-- Indexes
CREATE INDEX IDX_INV_SUPPLIER    ON SUPPLIER_INVOICE(SUPPLIER_ID);
CREATE INDEX IDX_INV_STATUS      ON SUPPLIER_INVOICE(STATUS);
CREATE INDEX IDX_INV_DATE        ON SUPPLIER_INVOICE(INVOICE_DATE);
CREATE INDEX IDX_INV_DUE         ON SUPPLIER_INVOICE(DUE_DATE);
CREATE INDEX IDX_IL_INVOICE      ON INVOICE_LINE(INVOICE_ID);
CREATE INDEX IDX_IL_PO           ON INVOICE_LINE(PO_ID);
CREATE INDEX IDX_IM_INVOICE      ON INVOICE_MATCH(INVOICE_ID);

-- Seed payment terms
INSERT INTO PAYMENT_TERM (TERM_CODE, TERM_NAME, NET_DAYS, DISCOUNT_DAYS, DISCOUNT_PCT)
    VALUES ('NET30', 'Net 30 Days', 30, NULL, 0);
INSERT INTO PAYMENT_TERM (TERM_CODE, TERM_NAME, NET_DAYS, DISCOUNT_DAYS, DISCOUNT_PCT)
    VALUES ('NET60', 'Net 60 Days', 60, NULL, 0);
INSERT INTO PAYMENT_TERM (TERM_CODE, TERM_NAME, NET_DAYS, DISCOUNT_DAYS, DISCOUNT_PCT)
    VALUES ('2_10_NET30', '2/10 Net 30 (2% discount if paid in 10 days)', 30, 10, 2);
INSERT INTO PAYMENT_TERM (TERM_CODE, TERM_NAME, NET_DAYS, DISCOUNT_DAYS, DISCOUNT_PCT)
    VALUES ('ADVANCE', '100% Advance Payment', 0, NULL, 0);
INSERT INTO PAYMENT_TERM (TERM_CODE, TERM_NAME, NET_DAYS, DISCOUNT_DAYS, DISCOUNT_PCT)
    VALUES ('LC90', 'Letter of Credit 90 Days', 90, NULL, 0);
INSERT INTO PAYMENT_TERM (TERM_CODE, TERM_NAME, NET_DAYS, DISCOUNT_DAYS, DISCOUNT_PCT)
    VALUES ('NET45', 'Net 45 Days', 45, NULL, 0);
COMMIT;

PROMPT [OK] Invoice matching tables created.
SELECT TABLE_NAME FROM USER_TABLES
WHERE TABLE_NAME IN ('PAYMENT_TERM','SUPPLIER_INVOICE','INVOICE_LINE','INVOICE_MATCH')
ORDER BY TABLE_NAME;
