-- ============================================================
-- MPPMS :: 41_qc_inspection_tables.sql
-- Purpose : QC Inspection with Steel-Specific Parameters
-- Run As  : MPPMS user on FREEPDB1
-- ============================================================
SET ECHO ON
SET FEEDBACK ON
SET DEFINE OFF

PROMPT ============================================================
PROMPT  MPPMS :: Phase 11d - QC Inspection Tables
PROMPT ============================================================

-- ── QC Parameter Templates (steel-specific) ─────────────────
CREATE TABLE QC_PARAMETER (
    PARAM_ID            NUMBER          GENERATED ALWAYS AS IDENTITY,
    MATERIAL_CATEGORY   VARCHAR2(50)    NOT NULL,  -- STRUCTURAL_STEEL / STEEL_COIL / etc.
    PARAMETER_NAME      VARCHAR2(100)   NOT NULL,
    PARAMETER_CODE      VARCHAR2(30)    NOT NULL,
    PARAMETER_TYPE      VARCHAR2(20)    DEFAULT 'NUMERIC',  -- NUMERIC / PASS_FAIL / TEXT
    UNIT                VARCHAR2(20),
    SPEC_MIN            NUMBER(18,4),
    SPEC_MAX            NUMBER(18,4),
    IS_MANDATORY        VARCHAR2(1)     DEFAULT 'Y',
    STANDARD_REF        VARCHAR2(100),  -- e.g. ASTM A36, IS 2062, EN 10025
    SORT_ORDER          NUMBER(3)       DEFAULT 10,
    CONSTRAINT PK_QC_PARAMETER  PRIMARY KEY (PARAM_ID),
    CONSTRAINT UQ_QC_PARAM      UNIQUE (MATERIAL_CATEGORY, PARAMETER_CODE)
);

-- ── QC Inspection Header ─────────────────────────────────────
CREATE TABLE QC_INSPECTION (
    INSPECTION_ID       NUMBER          GENERATED ALWAYS AS IDENTITY,
    INSPECTION_NUMBER   VARCHAR2(30)    NOT NULL,  -- QC-2026-000001
    GR_TRANSACTION_ID   NUMBER,         -- links to INVENTORY_TRANSACTION
    PO_ID               NUMBER,
    MATERIAL_ID         NUMBER          NOT NULL,
    SUPPLIER_ID         NUMBER,
    LOT_NUMBER          VARCHAR2(50),   -- links to LOT_MASTER
    WAREHOUSE_ID        NUMBER,
    INSPECTION_DATE     DATE            DEFAULT TRUNC(SYSDATE),
    INSPECTOR_NAME      VARCHAR2(100),
    TOTAL_QTY_RECEIVED  NUMBER(18,3)    NOT NULL,
    QTY_SAMPLED         NUMBER(18,3),
    QTY_ACCEPTED        NUMBER(18,3)    DEFAULT 0,
    QTY_REJECTED        NUMBER(18,3)    DEFAULT 0,
    QTY_UNDER_WAIVER    NUMBER(18,3)    DEFAULT 0,
    INSPECTION_STATUS   VARCHAR2(20)    DEFAULT 'PENDING',
    OVERALL_RESULT      VARCHAR2(15),   -- PASS / FAIL / CONDITIONAL
    MILL_CERT_RECEIVED  VARCHAR2(1)     DEFAULT 'N',
    MILL_CERT_NUMBER    VARCHAR2(100),
    HEAT_NUMBER         VARCHAR2(50),   -- steel mill heat/cast number
    WAIVER_REASON       VARCHAR2(500),  -- if CONDITIONAL acceptance
    NOTES               VARCHAR2(2000),
    COMPLETED_DATE      DATE,
    CREATED_DATE        DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_QC_INSPECTION     PRIMARY KEY (INSPECTION_ID),
    CONSTRAINT FK_QCI_MATERIAL      FOREIGN KEY (MATERIAL_ID)  REFERENCES MATERIAL_MASTER(MATERIAL_ID),
    CONSTRAINT FK_QCI_SUPPLIER      FOREIGN KEY (SUPPLIER_ID)  REFERENCES SUPPLIER_MASTER(SUPPLIER_ID),
    CONSTRAINT FK_QCI_PO            FOREIGN KEY (PO_ID)        REFERENCES PURCHASE_ORDER(PO_ID),
    CONSTRAINT UQ_INSPECTION_NUM    UNIQUE (INSPECTION_NUMBER),
    CONSTRAINT CHK_QCI_STATUS       CHECK (INSPECTION_STATUS IN ('PENDING','IN_PROGRESS','COMPLETED','CANCELLED')),
    CONSTRAINT CHK_QCI_RESULT       CHECK (OVERALL_RESULT IN ('PASS','FAIL','CONDITIONAL'))
);

-- ── QC Inspection Line (individual parameter results) ────────
CREATE TABLE QC_INSPECTION_LINE (
    LINE_ID             NUMBER          GENERATED ALWAYS AS IDENTITY,
    INSPECTION_ID       NUMBER          NOT NULL,
    PARAM_ID            NUMBER,
    PARAMETER_CODE      VARCHAR2(30)    NOT NULL,
    PARAMETER_NAME      VARCHAR2(100)   NOT NULL,
    UNIT                VARCHAR2(20),
    SPEC_MIN            NUMBER(18,4),
    SPEC_MAX            NUMBER(18,4),
    MEASURED_VALUE_NUM  NUMBER(18,4),   -- for numeric params
    MEASURED_VALUE_TEXT VARCHAR2(100),  -- for pass/fail or text params
    RESULT              VARCHAR2(10)    DEFAULT 'PENDING',   -- PASS / FAIL / N/A
    DEVIATION_PCT       NUMBER(8,3),    -- how far outside spec
    TEST_METHOD         VARCHAR2(100),  -- e.g. "ASTM E8 tensile test"
    NOTES               VARCHAR2(500),
    CONSTRAINT PK_QC_LINE       PRIMARY KEY (LINE_ID),
    CONSTRAINT FK_QCL_INSP      FOREIGN KEY (INSPECTION_ID) REFERENCES QC_INSPECTION(INSPECTION_ID),
    CONSTRAINT CHK_QCL_RESULT   CHECK (RESULT IN ('PASS','FAIL','N/A','PENDING'))
);

-- ── QC Return (rejected material back to supplier) ───────────
CREATE TABLE QC_RETURN (
    RETURN_ID               NUMBER          GENERATED ALWAYS AS IDENTITY,
    RETURN_NUMBER           VARCHAR2(30)    NOT NULL,  -- QCR-2026-000001
    INSPECTION_ID           NUMBER          NOT NULL,
    SUPPLIER_ID             NUMBER          NOT NULL,
    MATERIAL_ID             NUMBER,
    QTY_RETURNED            NUMBER(18,3)    NOT NULL,
    RETURN_DATE             DATE            DEFAULT TRUNC(SYSDATE),
    RETURN_REASON           VARCHAR2(500)   NOT NULL,
    FAILED_PARAMETERS       VARCHAR2(500),  -- comma-separated list
    RETURN_STATUS           VARCHAR2(20)    DEFAULT 'INITIATED',
    SUPPLIER_CREDIT_EXPECTED NUMBER(18,2),
    CURRENCY_CODE           VARCHAR2(3)     DEFAULT 'SAR',
    CREDIT_RECEIVED         NUMBER(18,2),
    CREDIT_DATE             DATE,
    REPLACEMENT_REQUESTED   VARCHAR2(1)     DEFAULT 'N',
    REPLACEMENT_DUE_DATE    DATE,
    NOTES                   VARCHAR2(1000),
    CREATED_DATE            DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_QC_RETURN     PRIMARY KEY (RETURN_ID),
    CONSTRAINT FK_QCR_INSP      FOREIGN KEY (INSPECTION_ID) REFERENCES QC_INSPECTION(INSPECTION_ID),
    CONSTRAINT FK_QCR_SUPPLIER  FOREIGN KEY (SUPPLIER_ID)   REFERENCES SUPPLIER_MASTER(SUPPLIER_ID),
    CONSTRAINT CHK_QCR_STATUS   CHECK (RETURN_STATUS IN ('INITIATED','DISPATCHED','RECEIVED_BY_SUPPLIER','CREDITED','REPLACED','CLOSED'))
);

-- Indexes
CREATE INDEX IDX_QCI_MATERIAL     ON QC_INSPECTION(MATERIAL_ID);
CREATE INDEX IDX_QCI_SUPPLIER     ON QC_INSPECTION(SUPPLIER_ID);
CREATE INDEX IDX_QCI_STATUS       ON QC_INSPECTION(INSPECTION_STATUS);
CREATE INDEX IDX_QCI_DATE         ON QC_INSPECTION(INSPECTION_DATE);
CREATE INDEX IDX_QCL_INSPECTION   ON QC_INSPECTION_LINE(INSPECTION_ID);
CREATE INDEX IDX_QCR_INSPECTION   ON QC_RETURN(INSPECTION_ID);

-- Sequence for inspection numbers
CREATE SEQUENCE SEQ_QC_INSPECTION_NUM START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_QC_RETURN_NUM    START WITH 1 INCREMENT BY 1;

-- ── Seed QC Parameters — Steel-Specific ─────────────────────
BEGIN

  -- STRUCTURAL_STEEL (H-Beams, I-Beams, Channels, Angles, Plates)
  -- Based on IS 2062, ASTM A36, EN 10025-2
  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STRUCTURAL_STEEL','TENSILE_STRENGTH','Tensile Strength','NUMERIC','MPa',410,550,'Y','IS 2062 / ASTM A36',10);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STRUCTURAL_STEEL','YIELD_STRENGTH','Yield Strength (0.2% proof)','NUMERIC','MPa',250,355,'Y','IS 2062 / EN 10025-2',20);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STRUCTURAL_STEEL','ELONGATION','Elongation at Break','NUMERIC','%',20,NULL,'Y','IS 2062',30);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STRUCTURAL_STEEL','CARBON_PCT','Carbon Content (C%)','NUMERIC','%',NULL,0.22,'Y','IS 2062',40);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STRUCTURAL_STEEL','MANGANESE_PCT','Manganese Content (Mn%)','NUMERIC','%',0.60,1.65,'Y','IS 2062',50);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STRUCTURAL_STEEL','PHOSPHORUS_PCT','Phosphorus Content (P%)','NUMERIC','%',NULL,0.035,'Y','IS 2062',60);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STRUCTURAL_STEEL','SULPHUR_PCT','Sulphur Content (S%)','NUMERIC','%',NULL,0.035,'Y','IS 2062',70);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STRUCTURAL_STEEL','CARBON_EQ','Carbon Equivalent (CE)','NUMERIC',NULL,NULL,0.42,'Y','IIW Formula',80);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STRUCTURAL_STEEL','MILL_CERT','Mill Test Certificate (MTC)','PASS_FAIL',NULL,NULL,NULL,'Y','IS 2062',90);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STRUCTURAL_STEEL','VISUAL_INSP','Visual & Dimensional Inspection','PASS_FAIL',NULL,NULL,NULL,'Y','IS 2062',100);

  -- STEEL_COIL (Hot Rolled / Cold Rolled Coils & Sheets)
  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STEEL_COIL','THICKNESS_MM','Thickness','NUMERIC','mm',NULL,NULL,'Y','IS 1079 / ASTM A1011',10);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STEEL_COIL','THICKNESS_TOL','Thickness Tolerance','NUMERIC','mm',-0.30,0.30,'Y','IS 1079',20);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STEEL_COIL','WIDTH_MM','Width','NUMERIC','mm',NULL,NULL,'Y','IS 1079',30);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STEEL_COIL','HARDNESS_HB','Hardness (Brinell)','NUMERIC','HB',NULL,217,'Y','ASTM A370',40);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STEEL_COIL','SURFACE_QUAL','Surface Quality Grade','PASS_FAIL',NULL,NULL,NULL,'Y','EN 10163',50);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STEEL_COIL','FLATNESS','Flatness (Max Bow per meter)','NUMERIC','mm/m',NULL,10,'N','EN 10029',60);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STEEL_COIL','MILL_CERT','Mill Test Certificate (MTC)','PASS_FAIL',NULL,NULL,NULL,'Y','IS 1079',70);

  -- STEEL_PIPE (ERW / Seamless Pipes)
  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STEEL_PIPE','OUTER_DIA','Outer Diameter','NUMERIC','mm',NULL,NULL,'Y','IS 1978 / API 5L',10);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STEEL_PIPE','WALL_THICK','Wall Thickness','NUMERIC','mm',NULL,NULL,'Y','IS 1978 / API 5L',20);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STEEL_PIPE','HYDRO_TEST','Hydrostatic Test','PASS_FAIL',NULL,NULL,NULL,'Y','IS 1978',30);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STEEL_PIPE','STRAIGHTNESS','Straightness (max dev per 3m)','NUMERIC','mm',NULL,3,'Y','IS 1978',40);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('STEEL_PIPE','MILL_CERT','Mill Test Certificate (MTC)','PASS_FAIL',NULL,NULL,NULL,'Y','API 5L',50);

  -- FASTENERS (Bolts, Nuts, Washers)
  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('FASTENERS','HARDNESS_HRC','Hardness (Rockwell C)','NUMERIC','HRC',26,34,'Y','ASTM F606',10);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('FASTENERS','TENSILE_STR','Tensile Strength','NUMERIC','MPa',830,1040,'Y','IS 1367',20);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('FASTENERS','THREAD_QUAL','Thread Quality (Go/No-Go)','PASS_FAIL',NULL,NULL,NULL,'Y','IS 1367',30);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('FASTENERS','GRADE_MARK','Grade Marking Verification','PASS_FAIL',NULL,NULL,NULL,'Y','IS 1367',40);

  -- WELDING_CONSUMABLES (Electrodes, Wire, Flux)
  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('WELDING_CONSUMABLES','MOISTURE_PCT','Moisture Content','NUMERIC','%',NULL,0.5,'Y','AWS A5.1',10);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('WELDING_CONSUMABLES','DEP_TENSILE','Deposited Metal Tensile Strength','NUMERIC','MPa',480,NULL,'Y','AWS A5.1',20);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('WELDING_CONSUMABLES','AWS_CLASS','AWS Classification Verification','PASS_FAIL',NULL,NULL,NULL,'Y','AWS A5.1',30);

  -- PAINT_COATING
  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('PAINT_COATING','VISCOSITY_KU','Viscosity (Krebs Units)','NUMERIC','KU',90,130,'Y','ASTM D562',10);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('PAINT_COATING','DFT_MICRON','Dry Film Thickness','NUMERIC','μm',NULL,NULL,'Y','SSPC-PA 2',20);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('PAINT_COATING','ADHESION','Adhesion Test','PASS_FAIL',NULL,NULL,NULL,'Y','ASTM D3359',30);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('PAINT_COATING','VOC_GL','VOC Content','NUMERIC','g/L',NULL,420,'N','EPA Method 24',40);

  -- GENERAL (catch-all for materials without a category)
  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('GENERAL','VISUAL_INSP','Visual Inspection','PASS_FAIL',NULL,NULL,NULL,'Y','Internal',10);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('GENERAL','DIM_CHECK','Dimensional Verification','PASS_FAIL',NULL,NULL,NULL,'Y','Drawing/Spec',20);

  INSERT INTO QC_PARAMETER (MATERIAL_CATEGORY, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_TYPE, UNIT, SPEC_MIN, SPEC_MAX, IS_MANDATORY, STANDARD_REF, SORT_ORDER)
  VALUES ('GENERAL','LABELLING','Labelling & Marking Check','PASS_FAIL',NULL,NULL,NULL,'Y','Internal',30);

  COMMIT;
END;
/

PROMPT [OK] QC Inspection tables and steel parameters created.
SELECT MATERIAL_CATEGORY, COUNT(*) AS PARAM_COUNT
FROM QC_PARAMETER
GROUP BY MATERIAL_CATEGORY
ORDER BY MATERIAL_CATEGORY;
