-- ============================================================
-- MPPMS :: 45_lot_serial_tables.sql
-- Purpose : Lot & Serial Number Tracking (ALL Materials)
-- Run As  : MPPMS user on FREEPDB1
-- ============================================================
SET ECHO ON
SET FEEDBACK ON
SET DEFINE OFF

PROMPT ============================================================
PROMPT  MPPMS :: Phase 11f - Lot & Serial Tracking Tables
PROMPT ============================================================

CREATE TABLE LOT_MASTER (
    LOT_ID              NUMBER          GENERATED ALWAYS AS IDENTITY,
    LOT_NUMBER          VARCHAR2(30)    NOT NULL,   -- LOT-2026-000001
    MATERIAL_ID         NUMBER          NOT NULL,
    SUPPLIER_ID         NUMBER,
    PO_ID               NUMBER,
    GR_TRANSACTION_ID   NUMBER,         -- the INVENTORY_TRANSACTION that received it
    QC_INSPECTION_ID    NUMBER,         -- links to QC_INSPECTION
    -- Steel traceability fields
    HEAT_NUMBER         VARCHAR2(50),   -- steel mill heat/cast number
    MILL_CERT_NUMBER    VARCHAR2(100),  -- mill test certificate ref
    COUNTRY_OF_ORIGIN   VARCHAR2(60),
    MILL_NAME           VARCHAR2(200),
    -- Dates
    MANUFACTURE_DATE    DATE,
    RECEIPT_DATE        DATE            DEFAULT TRUNC(SYSDATE),
    EXPIRY_DATE         DATE,           -- for paint, chemicals
    -- Quantities (all in primary UOM)
    QTY_RECEIVED        NUMBER(18,3)    NOT NULL,
    QTY_AVAILABLE       NUMBER(18,3)    DEFAULT 0,
    QTY_QUARANTINE      NUMBER(18,3)    DEFAULT 0,
    QTY_CONSUMED        NUMBER(18,3)    DEFAULT 0,
    QTY_REJECTED        NUMBER(18,3)    DEFAULT 0,
    -- Location
    WAREHOUSE_ID        NUMBER,
    BIN_ID              NUMBER,
    -- Status
    STATUS              VARCHAR2(20)    DEFAULT 'AVAILABLE',
    NOTES               VARCHAR2(1000),
    CREATED_DATE        DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_LOT_MASTER        PRIMARY KEY (LOT_ID),
    CONSTRAINT FK_LOT_MATERIAL      FOREIGN KEY (MATERIAL_ID)  REFERENCES MATERIAL_MASTER(MATERIAL_ID),
    CONSTRAINT FK_LOT_SUPPLIER      FOREIGN KEY (SUPPLIER_ID)  REFERENCES SUPPLIER_MASTER(SUPPLIER_ID),
    CONSTRAINT FK_LOT_PO            FOREIGN KEY (PO_ID)        REFERENCES PURCHASE_ORDER(PO_ID),
    CONSTRAINT UQ_LOT_NUMBER        UNIQUE (LOT_NUMBER),
    CONSTRAINT CHK_LOT_STATUS       CHECK (STATUS IN ('AVAILABLE','PARTIALLY_USED','CONSUMED','QUARANTINE','REJECTED','EXPIRED'))
);

CREATE TABLE LOT_TRANSACTION (
    TXN_ID              NUMBER          GENERATED ALWAYS AS IDENTITY,
    LOT_ID              NUMBER          NOT NULL,
    TRANSACTION_TYPE    VARCHAR2(20)    NOT NULL,
    QTY_CHANGE          NUMBER(18,3)    NOT NULL,   -- +ve = in, -ve = out
    QTY_AFTER           NUMBER(18,3),
    WAREHOUSE_ID        NUMBER,
    BIN_ID              NUMBER,
    REFERENCE_DOC_TYPE  VARCHAR2(30),   -- PO / WORK_ORDER / PROD_PLAN / ADJUSTMENT
    REFERENCE_DOC_ID    NUMBER,
    TRANSACTION_DATE    DATE            DEFAULT SYSDATE,
    PERFORMED_BY        VARCHAR2(60),
    NOTES               VARCHAR2(500),
    CONSTRAINT PK_LOT_TXN       PRIMARY KEY (TXN_ID),
    CONSTRAINT FK_LTXN_LOT      FOREIGN KEY (LOT_ID) REFERENCES LOT_MASTER(LOT_ID),
    CONSTRAINT CHK_LOT_TXN_TYPE CHECK (TRANSACTION_TYPE IN ('RECEIPT','QUARANTINE_IN','QUARANTINE_OUT','ISSUE','RETURN','TRANSFER','ADJUSTMENT','REJECT','EXPIRE'))
);

CREATE TABLE SERIAL_MASTER (
    SERIAL_ID           NUMBER          GENERATED ALWAYS AS IDENTITY,
    SERIAL_NUMBER       VARCHAR2(100)   NOT NULL,
    MATERIAL_ID         NUMBER          NOT NULL,
    LOT_ID              NUMBER,
    SUPPLIER_ID         NUMBER,
    PO_ID               NUMBER,
    -- Location
    WAREHOUSE_ID        NUMBER,
    BIN_ID              NUMBER,
    STATUS              VARCHAR2(20)    DEFAULT 'IN_STOCK',
    -- Dates
    RECEIVED_DATE       DATE            DEFAULT TRUNC(SYSDATE),
    ISSUED_DATE         DATE,
    RETURNED_DATE       DATE,
    SCRAPPED_DATE       DATE,
    WARRANT_EXPIRY      DATE,
    NOTES               VARCHAR2(500),
    CREATED_DATE        DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_SERIAL_MASTER     PRIMARY KEY (SERIAL_ID),
    CONSTRAINT FK_SER_MATERIAL      FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAL_MASTER(MATERIAL_ID),
    CONSTRAINT FK_SER_LOT           FOREIGN KEY (LOT_ID)      REFERENCES LOT_MASTER(LOT_ID),
    CONSTRAINT UQ_SERIAL_NUMBER     UNIQUE (SERIAL_NUMBER),
    CONSTRAINT CHK_SER_STATUS       CHECK (STATUS IN ('IN_STOCK','ISSUED','RETURNED','SCRAPPED','IN_REPAIR','LOST'))
);

CREATE TABLE SERIAL_TRANSACTION (
    TXN_ID              NUMBER          GENERATED ALWAYS AS IDENTITY,
    SERIAL_ID           NUMBER          NOT NULL,
    TRANSACTION_TYPE    VARCHAR2(20)    NOT NULL,
    FROM_WAREHOUSE_ID   NUMBER,
    FROM_BIN_ID         NUMBER,
    TO_WAREHOUSE_ID     NUMBER,
    TO_BIN_ID           NUMBER,
    REFERENCE_DOC_TYPE  VARCHAR2(30),
    REFERENCE_DOC_ID    NUMBER,
    TRANSACTION_DATE    DATE            DEFAULT SYSDATE,
    PERFORMED_BY        VARCHAR2(60),
    NOTES               VARCHAR2(500),
    CONSTRAINT PK_SERIAL_TXN        PRIMARY KEY (TXN_ID),
    CONSTRAINT FK_STXN_SERIAL       FOREIGN KEY (SERIAL_ID) REFERENCES SERIAL_MASTER(SERIAL_ID),
    CONSTRAINT CHK_SER_TXN_TYPE     CHECK (TRANSACTION_TYPE IN ('RECEIPT','ISSUE','RETURN','TRANSFER','SCRAP','REPAIR_OUT','REPAIR_IN'))
);

-- Indexes
CREATE INDEX IDX_LOT_MATERIAL       ON LOT_MASTER(MATERIAL_ID);
CREATE INDEX IDX_LOT_SUPPLIER       ON LOT_MASTER(SUPPLIER_ID);
CREATE INDEX IDX_LOT_STATUS         ON LOT_MASTER(STATUS);
CREATE INDEX IDX_LOT_EXPIRY         ON LOT_MASTER(EXPIRY_DATE);
CREATE INDEX IDX_LOT_HEAT           ON LOT_MASTER(HEAT_NUMBER);
CREATE INDEX IDX_LTXN_LOT           ON LOT_TRANSACTION(LOT_ID);
CREATE INDEX IDX_LTXN_DATE          ON LOT_TRANSACTION(TRANSACTION_DATE);
CREATE INDEX IDX_SER_MATERIAL       ON SERIAL_MASTER(MATERIAL_ID);
CREATE INDEX IDX_SER_STATUS         ON SERIAL_MASTER(STATUS);
CREATE INDEX IDX_STXN_SERIAL        ON SERIAL_TRANSACTION(SERIAL_ID);

-- Sequence for lot numbers
CREATE SEQUENCE SEQ_LOT_NUMBER  START WITH 1  INCREMENT BY 1  NOCACHE;
CREATE SEQUENCE SEQ_SERIAL_TXN  START WITH 1  INCREMENT BY 1  NOCACHE;

PROMPT [OK] Lot & Serial tracking tables created.
SELECT TABLE_NAME FROM USER_TABLES
WHERE TABLE_NAME IN ('LOT_MASTER','LOT_TRANSACTION','SERIAL_MASTER','SERIAL_TRANSACTION')
ORDER BY TABLE_NAME;
