SELECT 'POI' AS T, COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME='PURCHASE_ORDER_ITEMS'
UNION ALL
SELECT 'PO', COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME='PURCHASE_ORDER'
UNION ALL
SELECT 'WH', COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME='WAREHOUSE_MASTER'
UNION ALL
SELECT 'INV', COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME='INVENTORY_TRANSACTION'
UNION ALL
SELECT 'STOR', COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME='STORAGE_BIN'
ORDER BY 1, 2;
