SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME='SUPPLIER_MASTER' ORDER BY COLUMN_ID;
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME='MATERIAL_MASTER' ORDER BY COLUMN_ID;
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME='INVENTORY_BALANCE' ORDER BY COLUMN_ID;
